bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 1
full_bf16 = false
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
learning_rate = 2.3e-5
loss_type = "smooth_l1"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0.07
max_bucket_reso = 2560
max_data_loader_n_workers = 0
max_grad_norm = 0.5
max_timestep = 1000
max_token_length = 75
max_train_steps = 470
min_bucket_reso = 768
min_snr_gamma = 5
mixed_precision = "bf16"
network_alpha = 64
network_args = []
network_dim = 128
network_module = "networks.lora"
noise_offset_type = "Original"
optimizer_args = ["weight_decay=1e-2","betas=(0.9, 0.999, 0.9999)","eps=(1e-30, 1e-16)"]
optimizer_type = "pytorch_optimizer.CAME"
output_name = "jiangshen-NAIL6-MY"
prior_loss_weight = 1
resolution = "1152,1536"
sample_prompts = "/home/user/ai/lora/output/prompt.txt"
sample_sampler = "euler_a"
save_model_as = "safetensors"
save_precision = "bf16"
train_batch_size = 4
train_data_dir = "/home/user/ai/lora/training"
wandb_run_name = "jiangshen-NAIL6-MY"
xformers = true
flip_aug = true
face_crop_aug_range = "1.0,2.5"
network_dropout = 0.1