[paths]
base_directory = "/notebooks"
working_directory = "training"
program_directory = "program"
output_dir = "output"
model_dir = "model"
pretrained_model_name_or_path = "novaAsianXL_illustriousV70.safetensors"
temp_directory = "/tmp"
accelerate_path = "/venv/bin/accelerate"
kohya_directory = "/kohya_ss"
train_script_path = "/kohya_ss/sd-scripts/sdxl_train_network.py"

[accelerate_options]
dynamo_backend = "no"
dynamo_mode = "default"
mixed_precision = "bf16"
num_processes = 1
num_machines = 1
num_cpu_threads_per_process = 4

[train_options]
log_prefix = "xl-loha"

[makelora_settings]
output_suffix = "NA7"
train_config_file = "NAIL7-PSPACE.toml"

[modeldownload]
token = "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"

[[modeldownload.models]]
repo_id = "hstty/basemodel"
# filename is deprecated inside model entries. Use [paths].pretrained_model_name_or_path instead.

[rclone]
remote_path = "google:LORA"

